import { expect, test } from "bun:test"
import { SchematicTracePipelineSolver } from "lib/solvers/SchematicTracePipelineSolver/SchematicTracePipelineSolver"
import inputProblem from "./assets/repro-bq24074-battery-charger.input.json"
import "tests/fixtures/matcher"

// InputProblem extracted from a tscircuit circuit: a BQ24074RGTR Li-ion battery
// charger (U1) wired to a DC adapter header (J1), a 1uF input capacitor (C1)
// and a 3-pin battery pack header (BT1). Power/ground/signal nets connect the
// parts, and several U1 pins (N_PGOOD, N_CHG, ILIM, ITERM, ISET) break out to
// net labels. Generated by rendering the circuit in @tscircuit/core with
// DEBUG=Group_doInitialSchematicTraceRender and copying the emitted
// "group-trace-render-input-problem" output.
test("repro bq24074 battery charger", () => {
  const solver = new SchematicTracePipelineSolver(inputProblem as any)
  solver.solve()

  expect(solver).toMatchSolverSnapshot(import.meta.path)
})
