import { expect, test } from "bun:test"
import { SchematicTracePipelineSolver } from "lib/solvers/SchematicTracePipelineSolver/SchematicTracePipelineSolver"
import "tests/fixtures/matcher"
import inputProblem from "../bug-reports/bug-report-20260717-connector-crossing-674/input.json"

const findDifferentNetCrossings = (
  traces: Array<{
    mspPairId: string
    globalConnNetId: string
    tracePath: Array<{ x: number; y: number }>
  }>,
) => {
  const crossings: string[] = []
  for (let i = 0; i < traces.length; i++) {
    for (let j = i + 1; j < traces.length; j++) {
      const a = traces[i]!
      const b = traces[j]!
      if (a.globalConnNetId === b.globalConnNetId) continue
      for (let x = 0; x < a.tracePath.length - 1; x++) {
        for (let y = 0; y < b.tracePath.length - 1; y++) {
          const p1 = a.tracePath[x]!
          const p2 = a.tracePath[x + 1]!
          const q1 = b.tracePath[y]!
          const q2 = b.tracePath[y + 1]!
          const aIsHorizontal = Math.abs(p1.y - p2.y) < 1e-9
          const bIsHorizontal = Math.abs(q1.y - q2.y) < 1e-9
          if (aIsHorizontal === bIsHorizontal) continue
          const [h1, h2, v1, v2] = aIsHorizontal
            ? [p1, p2, q1, q2]
            : [q1, q2, p1, p2]
          if (
            v1.x > Math.min(h1.x, h2.x) + 1e-9 &&
            v1.x < Math.max(h1.x, h2.x) - 1e-9 &&
            h1.y > Math.min(v1.y, v2.y) + 1e-9 &&
            h1.y < Math.max(v1.y, v2.y) - 1e-9
          ) {
            crossings.push([a.mspPairId, b.mspPairId].sort().join(" x "))
          }
        }
      }
    }
  }
  return crossings.sort()
}

// Reproduction for https://github.com/tscircuit/schematic-trace-solver/issues/674
//
// Net-label connector traces generated by AvailableNetOrientationSolver are
// placed without checking whether they cross traces from other nets. Each
// perpendicular crossing renders as a false junction. On this board three
// crossings appear, e.g. the V3_3 connector slicing through the JP1.1-SJ3.1
// trace at (-7.1,-6.1).
//
// This test pins the CURRENT (buggy) behavior so the bug is tracked by CI.
// A fix should flip the assertion to .toEqual([]).
test("repro #674: net-label connector traces cross other nets' traces", () => {
  const solver = new SchematicTracePipelineSolver(inputProblem as any)
  solver.solve()

  const traces = solver.netLabelTraceCollisionSolver!.getOutput().traces

  // BUG: three different-net crossings, all involving generated connectors
  expect(findDifferentNetCrossings(traces)).toEqual([
    "JP1.1-SJ3.1 x available-net-orientation-3-V3_3",
    "U1.1-U1.3 x available-net-orientation-5-GND",
    "available-net-orientation-4-V3_3 x available-net-orientation-9-GND",
  ])

  expect(solver).toMatchSolverSnapshot(import.meta.path)
})
