import { expect, test } from "bun:test"
import { SchematicTracePipelineSolver } from "lib/solvers/SchematicTracePipelineSolver/SchematicTracePipelineSolver"
import "tests/fixtures/matcher"
import inputProblem from "../bug-reports/bug-report-20260717-connector-crossing-674/input.json"

const countDifferentNetCrossings = (
  traces: Array<{
    globalConnNetId: string
    tracePath: Array<{ x: number; y: number }>
  }>,
) => {
  let crossings = 0
  for (let i = 0; i < traces.length; i++) {
    for (let j = i + 1; j < traces.length; j++) {
      const a = traces[i]!
      const b = traces[j]!
      if (a.globalConnNetId === b.globalConnNetId) continue
      for (let x = 0; x < a.tracePath.length - 1; x++) {
        for (let y = 0; y < b.tracePath.length - 1; y++) {
          const p1 = a.tracePath[x]!
          const p2 = a.tracePath[x + 1]!
          const q1 = b.tracePath[y]!
          const q2 = b.tracePath[y + 1]!
          const aIsHorizontal = Math.abs(p1.y - p2.y) < 1e-9
          const bIsHorizontal = Math.abs(q1.y - q2.y) < 1e-9
          if (aIsHorizontal === bIsHorizontal) continue
          const [h1, h2, v1, v2] = aIsHorizontal
            ? [p1, p2, q1, q2]
            : [q1, q2, p1, p2]
          if (
            v1.x > Math.min(h1.x, h2.x) + 1e-9 &&
            v1.x < Math.max(h1.x, h2.x) - 1e-9 &&
            h1.y > Math.min(v1.y, v2.y) + 1e-9 &&
            h1.y < Math.max(v1.y, v2.y) - 1e-9
          ) {
            crossings++
          }
        }
      }
    }
  }
  return crossings
}

// https://github.com/tscircuit/schematic-trace-solver/issues/674
// Net-label connector traces generated by AvailableNetOrientationSolver were
// placed without checking whether they cross traces from other nets. On this
// board three crossings appeared (e.g. the V3_3 connector slicing through the
// JP1.1-SJ3.1 trace), each rendering as a false junction.
//
// Candidates whose connector crosses another net are now rejected when a
// crossing-free candidate exists. The remaining crossings on this board are
// pinned by the test.failing below: their pins are walled in by another
// net's trace on the shift axis, so avoiding them requires routing the
// connector around the blocking trace rather than shifting the anchor.
test.failing("net-label connector traces do not cross other nets' traces", () => {
  const solver = new SchematicTracePipelineSolver(inputProblem as any)
  solver.solve()

  const traces = solver.netLabelTraceCollisionSolver!.getOutput().traces
  expect(countDifferentNetCrossings(traces)).toBe(0)
})
