import { expect, test } from "bun:test"
import { SchematicTracePipelineSolver } from "lib/solvers/SchematicTracePipelineSolver/SchematicTracePipelineSolver"
import inputProblem from "./assets/repro-ina237-current-monitor.input.json"
import "tests/fixtures/matcher"

// InputProblem extracted from a tscircuit circuit: an INA237AQDGSRQ1 current/
// power monitor (U1) sensing across a 0.001Ω shunt (R_SHUNT) in the
// BUS_HIGH/LOAD_CHARGER path, with a 48V battery (B1), a 12V charger source
// (CHARGER), a load resistor (R_LOAD), I2C pull-ups (R1/R2/R3 to VS), a VS
// decoupling cap (C1) and an MCU I2C connector (J1). VS/SCL/SDA/N_ALERT/GND etc.
// break out to net labels. Generated by rendering the circuit in @tscircuit/core
// with DEBUG=Group_doInitialSchematicTraceRender and copying the emitted
// "group-trace-render-input-problem" output.
test("repro ina237 current monitor", () => {
  const solver = new SchematicTracePipelineSolver(inputProblem as any)
  solver.solve()

  expect(solver).toMatchSolverSnapshot(import.meta.path)
})
