import { expect, test } from "bun:test"
import { SchematicTracePipelineSolver } from "lib/solvers/SchematicTracePipelineSolver/SchematicTracePipelineSolver"
import "tests/fixtures/matcher"
import inputProblem from "./assets/repro-crystal-load-capacitors.input.json"

// InputProblem extracted from a tscircuit circuit: a 12MHz crystal (Y1) wired
// to two 22pF load capacitors (C19, C20) via the XIN and XOUT nets, with both
// capacitor bottom pins tied to GND. Generated by rendering the circuit in
// @tscircuit/core and capturing the "solver:started" event for
// SchematicTracePipelineSolver.
test("repro crystal with load capacitors routes XIN, XOUT, GND nets", () => {
  const solver = new SchematicTracePipelineSolver(inputProblem as any)

  const getPin = (pinId: string) =>
    solver.inputProblem.chips
      .flatMap((chip) => chip.pins)
      .find((pin) => pin.pinId === pinId)!

  expect(getPin("Y1.1").x).toBeCloseTo(getPin("C19.1").x)
  expect(getPin("Y1.2").x).toBeCloseTo(getPin("C20.1").x)
  expect(getPin("C19.2").y).toBeCloseTo(getPin("C20.2").y)

  solver.solve()

  expect(solver.schematicTraceLinesSolver?.failedConnectionPairs).toHaveLength(
    0,
  )
  expect(solver).toMatchSolverSnapshot(import.meta.path)
})
